import { createStore } from 'vuex'

const store = createStore({
  state: {
    fields: [
    {id: "a8", color: "light", display: "/assets/blackRook.svg"},
    {id: "b8", color: "dark", display: "/assets/blackKnight.svg"},
    {id: "c8", color: "light", display: "/assets/blackBishop.svg"},
    {id: "d8", color: "dark", display: "/assets/blackQueen.svg"},
    {id: "e8", color: "light", display: "/assets/blackKing.svg"},
    {id: "f8", color: "dark", display: "/assets/blackBishop.svg"},
    {id: "g8", color: "light", display: "/assets/blackKnight.svg"},
    {id: "h8", color: "dark", display: "/assets/blackRook.svg"},
    {id: "a7", color: "dark", display: "/assets/blackPawn.svg"},
    {id: "b7", color: "light", display: "/assets/blackPawn.svg"},
    {id: "c7", color: "dark", display: "/assets/blackPawn.svg"},
    {id: "d7", color: "light", display: "/assets/blackPawn.svg"},
    {id: "e7", color: "dark", display: "/assets/blackPawn.svg"},
    {id: "f7", color: "light", display: "/assets/blackPawn.svg"},
    {id: "g7", color: "dark", display: "/assets/blackPawn.svg"},
    {id: "h7", color: "light", display: "/assets/blackPawn.svg"},
    {id: "a6", color: "light", display: ""},
    {id: "b6", color: "dark", display: ""},
    {id: "c6", color: "light", display: ""},
    {id: "d6", color: "dark", display: ""},
    {id: "e6", color: "light", display: ""},
    {id: "f6", color: "dark", display: ""},
    {id: "g6", color: "light", display: ""},
    {id: "h6", color: "dark", display: ""},
    {id: "a5", color: "dark", display: ""},
    {id: "b5", color: "light", display: ""},
    {id: "c5", color: "dark", display: ""},
    {id: "d5", color: "light", display: ""},
    {id: "e5", color: "dark", display: ""},
    {id: "f5", color: "light", display: ""},
    {id: "g5", color: "dark", display: ""},
    {id: "h5", color: "light", display: ""},
    {id: "a4", color: "light", display: ""},
    {id: "b4", color: "dark", display: ""},
    {id: "c4", color: "light", display: ""},
    {id: "d4", color: "dark", display: ""},
    {id: "e4", color: "light", display: ""},
    {id: "f4", color: "dark", display: ""},
    {id: "g4", color: "light", display: ""},
    {id: "h4", color: "dark", display: ""},
    {id: "a3", color: "dark", display: ""},
    {id: "b3", color: "light", display: ""},
    {id: "c3", color: "dark", display: ""},
    {id: "d3", color: "light", display: ""},
    {id: "e3", color: "dark", display: ""},
    {id: "f3", color: "light", display: ""},
    {id: "g3", color: "dark", display: ""},
    {id: "h3", color: "light", display: ""},
    {id: "a2", color: "light", display: "/assets/whitePawn.svg"},
    {id: "b2", color: "dark", display: "/assets/whitePawn.svg"},
    {id: "c2", color: "light", display: "/assets/whitePawn.svg"},
    {id: "d2", color: "dark", display: "/assets/whitePawn.svg"},
    {id: "e2", color: "light", display: "/assets/whitePawn.svg"},
    {id: "f2", color: "dark", display: "/assets/whitePawn.svg"},
    {id: "g2", color: "light", display: "/assets/whitePawn.svg"},
    {id: "h2", color: "dark", display: "/assets/whitePawn.svg"},
    {id: "a1", color: "dark", display: "/assets/whiteRook.svg"},
    {id: "b1", color: "light", display: "/assets/whiteKnight.svg"},
    {id: "c1", color: "dark", display: "/assets/whiteBishop.svg"},
    {id: "d1", color: "light", display: "/assets/whiteQueen.svg"},
    {id: "e1", color: "dark", display: "/assets/whiteKing.svg"},
    {id: "f1", color: "light", display: "/assets/whiteBishop.svg"},
    {id: "g1", color: "dark", display: "/assets/whiteKnight.svg"},
    {id: "h1", color: "light", display: "/assets/whiteRook.svg"} 
    ]
  },
  mutations: { 
  },
  actions: {
  },
  modules: {
  }
})

export default store
